const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const context={module:{exports:{}}};vm.runInNewContext(fs.readFileSync('relay/Code.gs','utf8'),context);
const {exchange}=context.module.exports;
let state=null, now=1000;
const session='12345678-abcd-abcd-abcd-123456789abc';
function call(op,more={}){const r=exchange({op,session,...more},state,now,()=>session);state=r.state;return r.text;}
const observation={v:1,session,seq:1,x:0,z:0,can_harvest:true,fruit_count:0,fruit_capacity:10,previous_outcome:'NONE',
 tiles:[[0,0],[0,-1],[1,0],[0,1],[-1,0]].map(([x,z])=>({x,z,known:true,plant:'Apple',has_fruit:true,fruit_percent:100}))};
assert.equal(call('probe'),'PONG|1');assert.equal(call('start'),'SESSION|'+session);
assert.equal(call('observe',{observation}),'PENDING');
const deadline=state.pending.deadline_ms;
now+=3000;assert.equal(call('observe',{observation}),'PENDING');assert.equal(state.pending.deadline_ms,deadline);
assert.equal(call('observe',{observation:{...observation,seq:2}}),'ERROR|OUTSTANDING');
assert.equal(call('poll',{seq:1}),'PENDING');
assert.equal(JSON.parse(call('worker_poll')).observation.observation.seq,1);
assert.equal(call('worker_result',{seq:1,action:'HARVEST'}),'OK');
assert.equal(call('worker_result',{seq:1,action:'WAIT'}),'ERROR|CONFLICT');
assert.match(call('poll',{seq:1}),/^C\|.*\|1\|0\|0\|42000\|HARVEST$/);
assert.equal(call('ack',{seq:1,outcome:'HARVEST_CONFIRMED'}),'OK');
assert.equal(call('ack',{seq:1,outcome:'HARVEST_CONFIRMED'}),'OK');
assert.equal(call('poll',{seq:1}),'ERROR|SEQUENCE');
assert.equal(call('observe',{observation}),'ERROR|SEQUENCE');
assert.equal(call('observe',{observation:{...observation,seq:2}}),'PENDING');
assert.equal(call('cancel'),'OK');assert.equal(call('worker_result',{seq:2,action:'HARVEST'}),'ERROR|SEQUENCE');
assert.equal(call('observe',{observation:{...observation,seq:3}}),'PENDING');now+=45000;
assert.equal(call('worker_result',{seq:3,action:'HARVEST'}),'ERROR|EXPIRED');
assert.equal(call('observe',{session:'old-session',observation}),'ERROR|SESSION');
state=null;assert.equal(call('poll',{seq:1}),'ERROR|SESSION');
console.log('PASS: relay lifecycle, idempotence, stale results, cancellation, expiry, cache eviction');
// Test the deployed HTTP wrapper's role authentication with mocked Apps Script services.
let cache=null;
context.ContentService={MimeType:{TEXT:'text'},createTextOutput:s=>({setMimeType:()=>s})};
context.PropertiesService={getScriptProperties:()=>({getProperty:k=>k==='GAME_TOKEN'?'g'.repeat(64):'w'.repeat(64)})};
context.LockService={getScriptLock:()=>({tryLock:()=>true,releaseLock:()=>{}})};
context.CacheService={getScriptCache:()=>({get:()=>cache,put:(k,v)=>{cache=v}})};
context.Utilities={getUuid:()=>session};
const post=q=>context.doPost({postData:{contents:JSON.stringify(q)}});
assert.equal(post({op:'start',token:'wrong'}),'ERROR|AUTH');
assert.equal(post({op:'start',token:'w'.repeat(64)}),'ERROR|AUTH');
assert.equal(post({op:'worker_poll',token:'g'.repeat(64)}),'ERROR|AUTH');
assert.equal(post({op:'start',token:'g'.repeat(64)}),'SESSION|'+session);
assert.equal(JSON.parse(post({op:'worker_poll',token:'w'.repeat(64)})).session,session);
console.log('PASS: separate game/worker credentials and authenticated HTTP wrapper');
const get=q=>context.doGet({parameter:{q:JSON.stringify(q)}});
assert.match(context.doGet(),/relay v3/);
assert.equal(get({op:'probe',token:'g'.repeat(64)}),'PONG|1');
assert.equal(get({op:'probe',token:'bad'}),'ERROR|AUTH');
assert.equal(get({op:'worker_result',token:'w'.repeat(64)}),'ERROR|OP');
assert.equal(get({op:'worker_poll',token:'g'.repeat(64)}),'ERROR|OP');
assert.equal(context.doGet({parameter:{q:'{'}}),'ERROR|INVALID');
assert.equal(context.doGet({parameter:{q:'x'.repeat(16001)}}),'ERROR|REQUEST');
assert.equal(get({op:'start',token:'g'.repeat(64)}),'SESSION|'+session);
assert.equal(get({op:'observe',session,observation,token:'g'.repeat(64)}),'PENDING');
assert.equal(post({op:'worker_result',session,seq:1,action:'WAIT',token:'w'.repeat(64)}),'OK');
assert.match(get({op:'poll',session,seq:1,token:'g'.repeat(64)}),/\|WAIT$/);
assert.equal(get({op:'ack',session,seq:1,outcome:'WAIT',token:'g'.repeat(64)}),'OK');
console.log('PASS: game GET authentication, role isolation, malformed requests, GET/POST mailbox cycle');

call('start');
const mobile={...observation,autonomous:true,can_harvest:false};
assert.equal(call('observe',{observation:mobile}),'PENDING');
assert.equal(call('worker_result',{seq:1,action:'MOVE_EAST'}),'OK');
assert.match(call('poll',{seq:1}),/\|MOVE_EAST$/);
assert.equal(call('ack',{seq:1,outcome:'MOVED'}),'OK');
assert.equal(call('observe',{observation:{...mobile,seq:2,autonomous:false}}),'PENDING');
assert.equal(call('worker_result',{seq:2,action:'MOVE_NORTH'}),'ERROR|MOVE');
call('cancel');
assert.equal(call('observe',{observation:{...mobile,seq:3,tiles:mobile.tiles.map(t=>({...t,known:false}))}}),'PENDING');
assert.equal(call('worker_result',{seq:3,action:'MOVE_NORTH'}),'ERROR|MOVE');
console.log('PASS: neural move delivery, manual-mode rejection, unknown destination rejection');
